// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_multipleLRTest
List rcpp_multipleLRTest(NumericVector dev_vec, IntegerVector df_vec, NumericMatrix comparison_matrix);
RcppExport SEXP _logregHelper_rcpp_multipleLRTest(SEXP dev_vecSEXP, SEXP df_vecSEXP, SEXP comparison_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dev_vec(dev_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type df_vec(df_vecSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type comparison_matrix(comparison_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_multipleLRTest(dev_vec, df_vec, comparison_matrix));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_logregHelper_rcpp_multipleLRTest", (DL_FUNC) &_logregHelper_rcpp_multipleLRTest, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_logregHelper(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
