# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal rcpp function - Likelihood Ratio Test
#' @name Internal rcpp function - Likelihood Ratio Test
#'
#' @details Internal rcpp function that performs a likelihood ratio test between pairs of models. Returns the p-values and model indicies.
#'
#' @export
#' @examples
#' list_LR <-rcpp_multipleLRTest(m_dev, m_df, comparison_matrix)
#' @export
rcpp_multipleLRTest <- function(dev_vec, df_vec, comparison_matrix) {
    .Call(`_logregHelper_rcpp_multipleLRTest`, dev_vec, df_vec, comparison_matrix)
}

